a=[1,2,3,4,5,8,5]
print(a)
#for x in range(5):
   # x=int(input())
  #  a.append(x)
#print(a)
a.extend([1.3,1.5,1.7])
print(a)
a.insert(1,"Aman")
print(a)
#a.remove("Aman")
#print(a)
#a.remove(5)
print(a)
a.pop(1)
print(a)
print(a.pop(1))
a.pop()
print(a.count(5))
a.index(5)
a.sort()
print(a)
a.sort(reverse=True)
print(a)